### ISSUE TITLE
Your VS Code extension is affected by a security issue and have been blocked

### ISSUE THREAD

**Issue by auchenberg** [fr43nk/seito-openfile#17]
Hi,

Kenneth here from the VS Code team. 

Your extension is affected by https://code.visualstudio.com/blogs/2018/11/26/event-stream, and we have blocked your extension.

In order to enable your extension again the workflow is:
  
1) [ ] Fix the extension, submit an update to the marketplace
2) [ ] Send mail to VSMarketplace@microsoft.com and kennau@microsoft.com and notify us.
3) We will verify that the extension is okay
4) Our marketplace will publish the extension again and we'll remove the extension from the blocklist

/k

**Comment by johnnytemp** [comment]
Hi Frank, I would suggest to also remove seito-openfile-1.8.3.vsix in the git repository, which contain node_modules/flatmap-stream malicious code. Thanks.
