### ISSUE TITLE
Please add support for opening files from git diffs.

### ISSUE THREAD

**Issue by bwinton** [fr43nk/seito-openfile#4]
For some reason, git diffs list differences like this:
```diff
diff --git a/browser/components/downloads/content/downloads.css b/browser/components/downloads/content/downloads.css
--- a/browser/components/downloads/content/downloads.css
+++ b/browser/components/downloads/content/downloads.css
@@ -202,68 +202,8 @@ richlistitem.download button {
```
It would be nice if seito-openfile ignored the `a/` or `b/` at the start of these paths, so I could easily open them.  🙂

**Comment by johnnytemp** [comment]
Hi.

### This is now supported by this settings from version 1.8.0

    "seito-openfile.leadingPathMapping": {
        "a": "",
        "b": "",
    }

Note that if there is really a path "a/file.txt" with actual folder "a", "a/" will be removed from the look up.

Please try and close if ok.  Thank you.  :-)

**Comment by bwinton** [comment]
I can't seem to figure out what I was doing back then to trigger this, but the solution sounds good, so I'll close it. :)
