### ISSUE TITLE
Open shortened filenames

### ISSUE THREAD

**Issue by dutchwebworks** [fr43nk/seito-openfile#5]
Great plugin and saves a lot of time opening files! I work mostly with HTML/CSS/SCSS and JavaScript (frontend stuff). So I have a lot of `*.scss` files that have the following setup in so called Sass manifest files:

```scss
@import "scss/header";
@import "scss/footer";
```

On file-system the file is actually called: `scss/_header.scss` and `scss/_footer.scss`. So no underscore and no extension. The above notation of `@import` is valid SCSS syntax and works fine
 when compiling it to CSS using (Grunt/Gulp/Webpack/etc.).

Alas, **this plugin does not open the above shorter notation** of the file: `scss/header`. Only when I change it to the **full filename** `scss/_header.scss`, then this plugin does open that file.

Is it possible to have this plugin open 'shortened' filenames (more fuzzy searching)?

**Comment by fr43nk** [comment]
Hi, thank you very much.
I will try to make it work more fuzzy when using scss files. It is a good idea :)
