### ISSUE TITLE
Parsing line number broken since 1.4.0

### ISSUE THREAD

**Issue by stephanedr** [fr43nk/seito-openfile#6]
VSCode: 1.23.1
Extension: 1.5.0

A file name containing a line number doesn't open.
Reverting to 1.4.0: same issue.
Reverting to 1.3.4: file opens (at the expected line).

**Comment by fr43nk** [comment]
Thank you for reporting this bug.
I've fixed it in the current version **1.5.1**

**Comment by stephanedr** [comment]
Working fine. Thanks.
