### ISSUE TITLE
Support more extensions

### ISSUE THREAD

**Issue by jackfranklin** [fr43nk/seito-openfile#7]
Hello,

In JS we don't specify the extension when importing a file - so `import './foo'` should map to `foo.js`, or often in React, `foo.jsx`. I was wondering if you would consider supporting more extensions that could be looked for, along with SCSS?

Maybe `.js`, `.jsx`, `.scss` is a good start? Or it could be configurable?

**Comment by fr43nk** [comment]
Hi,
yes, I think it should be no problem adding a new configuration date to specify the extensions.
Thanks

**Comment by fr43nk** [comment]
Added the new configuration. Hope it works as expected :)
